./cub3D maps_test/ko_color_format.cub
./cub3D maps_test/ko_color_missing.cub
./cub3D maps_test/ko_color_neg.cub
./cub3D maps_test/ko_color_typo.cub
./cub3D maps_test/ko_missing_ext
./cub3D maps_test/ko_much_space.cub
./cub3D maps_test/ko_more_info_than_necessary_info.cub
./cub3D maps_test/ko_no_player.cub
./cub3D maps_test/ko_nonsense_map.cub
./cub3D maps_test/ko_player_in_walls.cub
./cub3D maps_test/ko_spaces.cub
./cub3D maps_test/ko_spaces_new_lines.cub
./cub3D maps_test/ko_spaces_text.cub
./cub3D maps_test/ko_texture_file_missing.cub
./cub3D maps_test/ko_texture_missing.cub
./cub3D maps_test/ko_texture_typo.cub
./cub3D maps_test/ko_wrong_char.cub
./cub3D maps_test/ko_wrong_ext.cub1
